### ISSUE TITLE
Ability to encode and decode ByteArrays

### ISSUE THREAD

**Issue by bgamari** [well-typed/cborg#136]
This will be necessary to allow for efficient serialisation of unboxed vectors.

**Comment by dcoutts** [comment]
Now done, in the 0.2 release with [encodeByteArray] / [decodeByteArray]

[encodeByteArray]: http://hackage.haskell.org/package/cborg-0.2.0.0/docs/Codec-CBOR-Encoding.html#v:encodeByteArray
[decodeByteArray]: http://hackage.haskell.org/package/cborg-0.2.0.0/docs/Codec-CBOR-Decoding.html#v:decodeByteArray
