### ISSUE TITLE
Extending exports of `serialise/src/Codec/Serialise/Class.hs`

### ISSUE THREAD

**Issue by ts468** [well-typed/cborg#138]
Would it be possible to extend the export list of `serialise/src/Codec/Serialise/Class.hs` for `GSerialiseProd` and `GSerialiseSum`?

I wanted to use the cborg library together with a custom type representation and so I would need to be able to add further instances besides e.g. `GSerialiseProd U1` or `GSerialiseProd (K1  i a)`.

**Comment by bgamari** [comment]
ts468 <notifications@github.com> writes:

> Would it be possible to extend the export list of `serialise/src/Codec/Serialise/Class.hs` for `GSerialiseProd` and `GSerialiseSum`?
>
> I wanted to use the cborg library together with a custom type representation and so I would need to be able to add further instances besides e.g. `GSerialiseProd U1` or `GSerialiseProd (K1  i a)`.
>
Hmm, I suppose I don't see why not. @dcoutts, any objection?

**Comment by ts468** [comment]
Thanks for considering the change, I've created a PR for it: #154.

**Comment by thoughtpolice** [comment]
I honestly would have done this when I originally accepted the serialization changes had I noticed... Maybe if you `blame` around I might even somehow be the culprit... SGTM in any case.

**Comment by ts468** [comment]
Closed with #154.
