### ISSUE TITLE
`Serialise` instance for Utf8-backed Text-type w/o UTF8<->UTF16<->UTF8 conversions

### ISSUE THREAD

**Issue by hvr** [well-typed/cborg#140]
I was trying to write an efficient instance for [`text-short`](https://hackage.haskell.org/package/text-short-0.1/docs/Data-Text-Short.html).

The main feature of `TextShort` is that internally it's an UTF8-encoded (NB: UTF8 invariant: no surrogates allowed) unpinned `ByteArray#` for compactness and the ability to avoid conversion overheads, as nowadays most on-disk/on-wire protocols use UTF8 for encoding "Text".

However, I don't see how to write an instance with the following properties:

 - `ShortText` is to be encoded as CBOR major type 3
 - The CBOR encoder & decoder shall not go via a futile UTF8<->UTF16<->UTF8 back/forth conversion

Am I missing something, or does the current API really not allow me to satisfy these requirements? Assuming my pessimism is spot on, what would need to be changed in `cborg` to make this possible?

**Comment by bgamari** [comment]
Herbert Valerio Riedel <notifications@github.com> writes:

> I was trying to write an efficient instance for [`text-short`](https://hackage.haskell.org/package/text-short-0.1/docs/Data-Text-Short.html).
>
> The main feature of `TextShort` is that internally it's an UTF8-encoded (NB: UTF8 invariant: no surrogate pairs allowed) unpinned `ByteArray#` for compactness and the ability to avoid conversion overheads, as nowadays most on-disk/on-wire protocols use UTF8 for encoding "Text".
>
> However, I don't see how to write an instance with the following properties:
>
>  - `ShortText` is to be encoded as CBOR major type 3
>  - The CBOR encoder & decoder shall not go via a futile UTF8<->UTF16<->UTF8 back/forth conversion
>
> Am I missing something, or does the current API really not allow me to
> satisfy these requirements?
>
The solution here is to add ByteArray text/bytestring paths to Read and
Write. This is #136. I haven't had a chance to do this yet.

Cheers,

- Ben

**Comment by dcoutts** [comment]
Now done, in the 0.2 release with [encodeUtf8ByteArray] / [decodeUtf8ByteArray]

[encodeUtf8ByteArray]: http://hackage.haskell.org/package/cborg-0.2.0.0/docs/Codec-CBOR-Encoding.html#v:encodeUtf8ByteArray
[decodeUtf8ByteArray]: http://hackage.haskell.org/package/cborg-0.2.0.0/docs/Codec-
