### ISSUE TITLE
Add static information to Decoder for canonical/non-canonical variants

### ISSUE THREAD

**Issue by arybczak** [well-typed/cborg#148]
When #147 gets merged, we'll have variants of decoders that accept any valid representation vs the ones that accept only canonical representation. Representing it in types would allow clients to statically guarantee they are using one or the other.

Here's an example of how that could look:
```haskell
{-# LANGUAGE EmptyDataDecls #-}

data NonCanonical

data Decoder c s a

instance Functor (Decoder c s) where
  fmap = undefined

instance Applicative (Decoder c s) where
  pure = undefined
  (<*>) = undefined

instance Monad (Decoder c s) where
  (>>=) = undefined

----------

decodeListLenCanonical :: Decoder canonical s Int
decodeListLenCanonical = undefined

decodeIntCanonical :: Decoder canonical s Int
decodeIntCanonical = undefined

decodeInt :: Decoder NonCanonical s Int
decodeInt = undefined

----------

myDecoder :: Decoder canonical s (Int, Int)
myDecoder = do
  2 <- decodeListLenCanonical
  -- We can't use decodeInt here.
  (,) <$> decodeIntCanonical <*> decodeIntCanonical
```

**Comment by bgamari** [comment]
Hmm, this seems awfully invasive for something that relatively few users have a need for. At very least `Decoder` should remain a quantified synonym over a `Decoder'` type exposing the canonical argument,
```haskell
type Decoder' s a = forall c. Decoder c s a
```

Alternatively, we could provide another module (`Codec.Cborg.Decoder.Canonical` or perhaps just `Codec.Serialise.Decoder`) which provides a newtype'd, canonical-annotated version of the current `Decoder` module,
```haskell
newtype Decoder canonical s a = Decoder (Codec.Cborg.Decoder.Decoder s a)
```

**Comment by dcoutts** [comment]
I agree, I don't think a type based approach is warranted here.
