### ISSUE TITLE
Usable incremental deserialize API for streaming - not in ST moand

### ISSUE THREAD

**Issue by ondrap** [well-typed/cborg#156]
I wasn't following the development for some time and now I see the `deserialiseIncremental` runs in `ST` monad. This makes it quite unusable for any incremental situation as there is usually some (network, filesystem) read in between the decoding steps and e.g. in the absence of some length information I don't even know how much data is needed.
Is there any deep reason to use the `ST` monad? Would it be possible to get back to the original approach without it?

**Comment by bgamari** [comment]
> Is there any deep reason to use the ST monad? 

Indeed there is: to allow principled use of mutation during deserialisation This is crucial to efficiently deserialsing dense structures like arrays.

However, the use of `ST` is not at all at odds with streaming. Rather, you just need to use `Control.Monad.ST.stToIO` ([haddocks](https://hackage.haskell.org/package/base-4.10.0.0/docs/Control-Monad-ST.html#v:stToIO). For instance,

```haskell
{-# LANGUAGE TypeApplications #-}
import Codec.CBOR.Read
import Codec.Serialise.Class (decode)
import qualified Data.ByteString as BS
import System.IO
import Control.Monad.ST.Strict

main = withFile "a-file" ReadMode $ \hdl -> do
    s0 <- stToIO $ deserialiseIncremental (decode @(Maybe Int))
    streamIt hdl s0

streamIt :: Handle -> IDecode RealWorld a -> IO a
streamIt hdl (Partial k) = do
    dec <- BS.hGet hdl 16 >>= stToIO . k . Just
    streamIt hdl dec
streamIt hdl (Done rest _ x) = return x
streamIt hdl (Fail rest _ e) = fail $ show e
```

**Comment by ondrap** [comment]
Oh, my fault, I didn't know the `stToIO` function... thanks.

**Comment by dcoutts** [comment]
We could perhaps make this clearer and easier to use by abstracting IDecode over the monad instead of the ST param s, and then providing two versions

    deserialiseIncremental   :: Serialise a => ST s (IDecode (ST s) a)
    deserialiseIncrementalIO :: Serialise a => IO   (IDecode IO a)

**Comment by matchwood** [comment]
Using `stToIO` does carry the rather crucial constraint that you have to be in `IO`.  So as I understand it, `ST` _is_ at odds with streaming - it just so happens that there is a workaround if you are in `IO`.

**Comment by edsko** [comment]
Yes, this needs better documentation... also, having to rely on `stToIO`........ :-o

**Comment by edsko** [comment]
In case this is useful to anyone else, here's a translation from `IDecode` to a type that doesn't involve `ST`:

```haskell
data IDecodeIO a =
    PartialIO (Maybe Strict.ByteString -> IO (IDecodeIO a))
  | DoneIO Strict.ByteString ByteOffset a
  | FailIO Strict.ByteString ByteOffset DeserialiseFailure

fromIDecode :: IDecode RealWorld a -> IDecodeIO a
fromIDecode (Partial f)      = PartialIO $ fmap fromIDecode . stToIO . f
fromIDecode (Done bs bo a)   = DoneIO bs bo a
fromIDecode (Fail bs bo err) = FailIO bs bo err

deserialiseIncrementalIO :: Serialise a => IO (IDecodeIO a)
deserialiseIncrementalIO = fromIDecode <$> stToIO deserialiseIncremental
```

And this is the incremental decoder wrapper that I use:

```haskell
data Decoder = Decoder {
    getChunk :: IO (Maybe Strict.ByteString)
  , leftover :: IORef Strict.ByteString
  }

initDecoder :: MonadIO m
            => IO (Maybe Strict.ByteString)
            -> m Decoder
initDecoder getChunk = do
    leftover <- liftIO $ newIORef Strict.empty
    return Decoder{..}

decodeValue :: (MonadIO m, Serialise a) => Decoder -> m a
decodeValue Decoder{..} = liftIO $ do
    decodeState <- deserialiseIncrementalIO
    case decodeState of
      DoneIO _ _ a   -> return a
      FailIO _ _ err -> throwIO err
      PartialIO k    -> go =<< k . Just =<< readIORef leftover
  where
    go :: IDecodeIO a -> IO a
    go (DoneIO bs _ a)  = writeIORef leftover bs >> return a
    go (FailIO _ _ err) = throwIO err
    go (PartialIO k)    = go =<< k =<< getChunk
```

May or may not be useful to someone :)
