### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by parsonsmatt** [well-typed/cborg#171]
We are currently depending on the master branch of `cborg` for the `cardano-sl` project. The commit we need has been pulled into `master`. Would it be possible to have a Hackage release?

Comparison: https://github.com/well-typed/cborg/compare/cborg-0.2.0.0...master

Thanks!

**Comment by thoughtpolice** [comment]
I plan on fixing up a few extra things (in particular it would be good to bring back the 32-bit Windows CI) before doing this, as well as investigate a few other things, but yes, I'd like to do it pretty soon.

(Out of curiosity, what fix did you need precisely?)

**Comment by parsonsmatt** [comment]
The note I have when I was researching this is "Has support for canonical cbor."

Thanks! :smile:

**Comment by maoe** [comment]
This would be great. I think this is the last issue for ghc-dump-core to support GHC 8.6.

**Comment by bgamari** [comment]
I can try to get to this today. Sorry for the wait!

**Comment by bgamari** [comment]
Done. Thanks for your patience!

**Comment by parsonsmatt** [comment]
Thanks so much :smile:

**Comment by maoe** [comment]
Thanks!
