### ISSUE TITLE
Please allow building with half 0.3.x

### ISSUE THREAD

**Issue by peti** [well-typed/cborg#174]
`cborg` excludes `half >= 0.3`, but when that constraint is lifted the build actually succeeds fine. Would it be possible to lift that constraint in the Cabal file?

http://packdeps.haskellers.com/feed?needle=cborg

**Comment by bgamari** [comment]
Peter Simons <notifications@github.com> writes:

> `cborg` excludes `half >= 0.3`, but when that constraint is lifted the
> build actually succeeds fine. Would it be possible to lift that
> constraint in the Cabal file?
>
Assuming the testsuite passes this seems reasonable to me.

**Comment by thoughtpolice** [comment]
Note that I have also retroactively released revisions for the `cborg/serialise` 2.0.0.0 packages to properly allow half-0.3, as well.
