### ISSUE TITLE
Add `cborg-json` to Stackage?

### ISSUE THREAD

**Issue by Gabriel439** [well-typed/cborg#191]
Would it be possible to add `cborg-json` to Stackage.  I was thinking of adding a `cborg-json` dependency to `dhall` (which is on Stackage) which would require adding `cborg-json` to Stackage, too.  I can technically add `cborg-json` to Stackage myself under my own account but it's usually considered better etiquette to request if the package owner can add it

**Comment by Gabriel439** [comment]
@bgamari: Thank you! 🙂

**Comment by mihaimaruseac** [comment]
Done, it will be in today's nightly

**Comment by thoughtpolice** [comment]
Closing since this is taken care of, thanks @bgamari
