### ISSUE TITLE
Aeson.decode fails to decode large .json file

### ISSUE THREAD

**Issue by hyiltiz** [well-typed/cborg#192]
I had a .json file containing highly nested data about 100Mb in size. When I run `cbor-tool encode --json large.json`, it fails with the error: `cbor-tool: user error (invalid JSON file!)`. However, I can successfully load this file using the R package `jsonlite::formJSON()`, so I am assuming it may have something to do with the file size.

**Comment by thoughtpolice** [comment]
The error case in question is only encountered when `aeson` (which is what `cbor-tool` uses) *itself* cannot parse the file, see here: https://github.com/well-typed/cborg/blob/master/cbor-tool/Main.hs#L38

Can you parse this file using Aeson alone, e.g. in GHCi? If not, this is likely a bug with aeson itself.

**Comment by hyiltiz** [comment]
Yes, it saw where that error came from. Tried in GHCi `liftM Data.Aeson.eitherDecode (Data.ByteString.Lazy.readFile "large.json")` and got this error: `Left "Error in $: Failed reading: not a valid json value"`.  Tried following the source code for `eitherDecode` to see who threw that error, but wasn't quite obvious.

**Comment by llelf** [comment]
Error messages are pathetic, yes.

@hyiltiz check there aren't any /* comments */ in your json.
 jsonlite allows them.

**Comment by hyiltiz** [comment]
I do not think there are any comments. I checked with `ag '/\*' large.json` which returned no results. I produced the file by serializing a large data structure mainly using Matlab's jsonencode [1] function. I wonder if some NaN and Inf values are actually the culprit here. 

[1] https://www.mathworks.com/help/matlab/ref/jsonencode.html

**Comment by hyiltiz** [comment]
Seems to be false alarm. I found that the large file is not read by jsonlite either. I let the same program produce a x10 smaller .json file (by simply decreasing the number of simulations from 10,000 to 1000). Now both jsonlite and cborg can read it.
