### ISSUE TITLE
cborg fails to compile when optimize-gmp is disabled

### ISSUE THREAD

**Issue by jkachmar** [well-typed/cborg#193]
When compiling `cborg-0.2.1.0` on Alpine Linux, with a version of GHC 8.4.4 that uses `integer-simple` rather than `integer-gmp`, compilation fails with the following error when the `optimize-gmp` flag is disabled:
```
    Configuring cborg-0.2.1.0...
    Preprocessing library for cborg-0.2.1.0..
    Building library for cborg-0.2.1.0..
    [ 1 of 14] Compiling Codec.CBOR.ByteArray.Internal ( src/Codec/CBOR/ByteArray/Internal.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Codec/CBOR/ByteArray/Internal.o )
    [ 2 of 14] Compiling Codec.CBOR.ByteArray.Sliced ( src/Codec/CBOR/ByteArray/Sliced.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Codec/CBOR/ByteArray/Sliced.o )
    [ 3 of 14] Compiling Codec.CBOR.ByteArray ( src/Codec/CBOR/ByteArray.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Codec/CBOR/ByteArray.o )
    [ 4 of 14] Compiling Codec.CBOR.Decoding ( src/Codec/CBOR/Decoding.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Codec/CBOR/Decoding.o )
    [ 5 of 14] Compiling Codec.CBOR.Encoding[boot] ( src/Codec/CBOR/Encoding.hs-boot, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Codec/CBOR/Encoding.o-boot )
    [ 6 of 14] Compiling Codec.CBOR.FlatTerm[boot] ( src/Codec/CBOR/FlatTerm.hs-boot, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Codec/CBOR/FlatTerm.o-boot )
    [ 7 of 14] Compiling Codec.CBOR.Encoding ( src/Codec/CBOR/Encoding.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Codec/CBOR/Encoding.o )
    [ 8 of 14] Compiling Codec.CBOR.FlatTerm ( src/Codec/CBOR/FlatTerm.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Codec/CBOR/FlatTerm.o )
    [ 9 of 14] Compiling Codec.CBOR.Magic ( src/Codec/CBOR/Magic.hs, .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/Codec/CBOR/Magic.o )
    
    /tmp/stack-8946806a04ac58ea/cborg-0.2.1.0/src/Codec/CBOR/Magic.hs:479:34: error:
        Variable not in scope: unsafeShiftL :: t -> Integer -> t
        |
    479 |         Just (w, ws') -> go (acc `unsafeShiftL` 8 + fromIntegral w) ws'
        |   
```
...as far as I can tell, the issue is due to the interaction of the following code blocks:
https://github.com/well-typed/cborg/blob/master/cborg/src/cbits/cbor.h#L4-L19
https://github.com/well-typed/cborg/blob/master/cborg/src/Codec/CBOR/Magic.hs#L110-L112
https://github.com/well-typed/cborg/blob/master/cborg/src/Codec/CBOR/Magic.hs#L490

It appears that the `integer-simple`-supporting code requires `unsafeShiftL`, which is exclusively gated behind an unrelated macro definition that checks for GHC version and underlying host architecture.

Since I'm compiling this with GHC 8.4.4 on an x86_64-based Alpine machine it would seem like these flags are both true, and therefore the CPP excludes this import, causing the module to fail to compile.

**Comment by dcoutts** [comment]
@jkachmar so can we declare this closed with your PR merged?

**Comment by bgamari** [comment]
Duncan Coutts <notifications@github.com> writes:

> @jkachmar so can we declare this closed with your PR merged?
>
Even if so we should probably test this configuration under CI.

**Comment by dcoutts** [comment]
Opened #207
