### ISSUE TITLE
Serialise a complex object in constant space?

### ISSUE THREAD

**Issue by cevantes** [well-typed/cborg#197]
I have a large complex object in memory that I want to serialise incrementally (and store to disk) without exploding RAM. I don't know if it is a difficult problem in general, but my object is mostly composed of Maps/Sets/Lists, so I think there should be a way to do that. But even a simple quickcheck-generated Map does not seem to fit constant space. Or should I be doing something wrong?

**Comment by axman6** [comment]
I'm not sure if this what you're after, but if you use `Codec.CBOR.Write.toBuilder`, you can then write that to a file handle using `Data.Bytestring.Builder.hPutBuilder`.

**Comment by dcoutts** [comment]
It doesn't even need anything special, even the normal `toLazyByteString` function will produce the results incrementally, so if you use the normal lazy bytestring file I/O then you'll get exactly the behaviour you're after.

Or to put it another way, yes the library is already designed that way. Many applications already successfully take advantage of this approach of writing out a snapshot of a large data structure.

Perhaps you have a more specific problem? If so, you'll need to explain the details. Test case etc.

**Comment by cevantes** [comment]
Thanks, I probably experience a memory leak somewhere.
