### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by neil-da** [well-typed/cborg#202]
The PR #195 is essential for our project as we don't use GMP - any chance of making a release that includes it? At the moment we're pulling directly from GitHub.

**Comment by dcoutts** [comment]
Lets try and get #200 #203 and #204 passing CI and merged. Excellent time for a release.

**Comment by thoughtpolice** [comment]
This is now done, thanks to Ben.

**Comment by thoughtpolice** [comment]
(See #215)
