### ISSUE TITLE
MonadFail causes benchmarks to fail.

### ISSUE THREAD

**Issue by AndreasPK** [well-typed/cborg#209]
When building benchmarks:

```
bench\versus\Macro\Load.hs:154:9: error:
    ‘fail’ is not a (visible) method of class ‘Monad’
    |
154 |         fail s = ParseFailed (FromString s Nothing)
    |         ^^^^


```

**Comment by sjakobi** [comment]
#217 probably fixed this.

**Comment by thoughtpolice** [comment]
Yes, without version info on the compiler it's harder for me to see what constraints would have resulted in a failure. I'm willing to bet @sjakobi is correct that his changes fix it, though. Closing, but feel free to re-open!
