### ISSUE TITLE
THalf NaN /= THalf NaN

### ISSUE THREAD

**Issue by sjakobi** [well-typed/cborg#211]
The Haskell implementation of Dhall currently relies on `Term`'s `Eq` instance to determine the equivalence of `Double` literals. The assumption was, that `Term`'s `Eq` instance would correspond to the equivalence of the CBOR-serialized bytes. For `THalf NaN` this isn't the case.

Is this a bug in the `Eq` instance or a misunderstanding about how the `Eq` instance should work?

**Comment by ocharles** [comment]
Well `Eq Term` is just the generically derived `Eq` instance, which is in turn using `Double` `==` (which is not equal for NaNs). It seems like maybe `dhall` should be encoding the `Term` and then comparing the resulting bytes (note it's not enough to compare the `Token`s, as `Token` has the same problem).

**Comment by sjakobi** [comment]
In hindsight, this wasn't a good idea.
