### ISSUE TITLE
Release/revision for GHC 8.8

### ISSUE THREAD

**Issue by quasicomputational** [well-typed/cborg#215]
At least `cborg-json` has bounds ruling out GHC 8.8 that are relaxed in HEAD. Could there be a release/revision there, please?

**Comment by sjakobi** [comment]
Bump! :)

**Comment by thoughtpolice** [comment]
I unfortunately don't have the ability to do revisions for the uploaded packages, so I'm tentatively assigning this to @bgamari (to defer, or do when his queue is empty).

**Comment by sjakobi** [comment]
It would be nice if #218 and https://github.com/well-typed/cborg/pull/217 could be included in the new releases.

**Comment by sjakobi** [comment]
Since https://github.com/well-typed/cborg/pull/217 has ensured that this project builds and tests cleanly with GHC-8.8, all that's missing is a release! :)

**Comment by thoughtpolice** [comment]
@bgamari ping

**Comment by sjakobi** [comment]
Ping @bgamari! :)

 `cborg-json` is the last package blocking support for GHC-8.8 in`dhall`.

**Comment by thoughtpolice** [comment]
I apparently do actually have maintainer privileges for the cborg packages, so I'll see if I can ping Ben and do a release sometime today.

**Comment by bgamari** [comment]
Sounds good to me. Thank you @thoughtpolice!

**Comment by sjakobi** [comment]
Any news on this @thoughtpolice? :)

**Comment by thoughtpolice** [comment]
I was at a big work conference this past week, so my bandwidth was very limited, sorry! (I was trying to sort out version numbers and left the next day.) I'll look at it this weekend since I'm playing catch up.

**Comment by DanBurton** [comment]
Bump

**Comment by sjakobi** [comment]
Ping @thoughtpolice! :)

**Comment by sjakobi** [comment]
@thoughtpolice Would it help if I submit a PR that updates the version numbers and changelogs?

**Comment by thoughtpolice** [comment]
@sjakobi Yes, apologies. Unfortunately Thanksgiving just happened in the US but I don't have plans to leave any time soon. I do still need to review one or two PRs; I'll get to that this afternoon.

**Comment by sjakobi** [comment]
@thoughtpolice See https://github.com/well-typed/cborg/pull/221.

**Comment by thoughtpolice** [comment]
And of course in a twist of fate I double checked and can update everything *except* `cborg-tool`. I'll ping @dcoutts or Ben privately to see if that can get fixed.

**Comment by sjakobi** [comment]
@thoughtpolice I don't think that missing permissions for `cborg-tool` need to delay the release of the other packages – looking again at the change history the only substantial change raised the lower bound on `base` from `4.6` to `4.7`.

Personally I only care about `cborg-json` and its dependencies.

**Comment by thoughtpolice** [comment]
Good point! Luckily Ben has also given me access to everything now (I hope), so I'll try to sort this out this morning after a meeting.

**Comment by sjakobi** [comment]
Ping @thoughtpolice.

Is there anything else that I could do to help get this release on Hackage?

If you can't find the time, please consider letting someone else do the upload, like @bgamari.

If none of you can find the time, I'd offer to do the upload if you add me (sjakobi) as a maintainer on Hackage.

**Comment by sjakobi** [comment]
Ping @thoughtpolice @bgamari!

**Comment by domenkozar** [comment]
This is the last package blocking GHC 8.8 for cachix :)

**Comment by bgamari** [comment]
Sigh, very sorry about this. Yes, I'm just going to take care of this tonight.

**Comment by bgamari** [comment]
I think we can finally put this issue to bed with:
* `cbor-tool-0.2.2.0`
* `cborg-0.2.2.1`
* `cborg-json-0.2.2.0`
* `serialise-0.2.2.0`

**Comment by sjakobi** [comment]
Woohoo! Many thanks @bgamari! :)

**Comment by thoughtpolice** [comment]
I apologize for the delay here as well; I had a severe dental infection that put me out for nearly two weeks and has only become manageable in the past few days, hence my sudden absence. Of course, now I have two more weeks of things (Nix, my own projects, work, this) backed up, too...

@bgamari, I would like to take this time to also propose we go ahead and add @sjakobi to the maintainers list for these packages as he asked earlier, and give commit rights. Simon has repeatedly shown good diligence and hard work, and extreme patience with our (perhaps now infamous) latency, which I think is fine qualification. While I authored/laid out a significant amount of the code here, and I am personally using cborg still for many things, it is largely "complete" for my needs at this time. (I suspect this is also true of many of our users; the fact it mostly works well is part of the reason so few people are generally willing to step up to things!)

Personally I support this already, so if you do as well Ben, I think we should just do it. I would essentially only ask that you (Simon) use good judgement in committing things yourself vs asking for review from us, and just try to coordinate releases by pinging us and letting us know. (Generally, it is much easier to spend my time on doing code reviews vs other administrative tasks such as doing uploads; this is something we should (and could!) really fix through our CI system or something, but is not something I've thought about.)

**Comment by sjakobi** [comment]
I'm happy to hear that your health is better again, @thoughtpolice, and thanks for the kind words! :)

I would gladly accept commit and Hackage permissions, and I promise not to abuse these in any way.

Note, though, that I don't currently intend to take a particularly active role in this project either – I'm mostly interested in it as a dependency of `dhall`.

**Comment by bgamari** [comment]
I am certainly not opposed to granting @sjakobi commit rights. Thanks @sjakobi !

**Comment by thoughtpolice** [comment]
> Note, though, that I don't currently intend to take a particularly active role in this project either – I'm mostly interested in it as a dependency of dhall.

In my view, I don't think you'd need to do much, honestly. The thing is, you've actively shown the desire to actively cajole us and try to keep things moving, and in reality, I think it would mainly be responding to issues like this one: it really shouldn't take months for a new package to be uploaded! It's just that all of us are fairly busy with many other things these days.

In reality, I expect that, if anything, you might only have to exercise your New Powers(TM) to... help prevent things like this from happening again, i.e. push changelogs and synchronize release info with us. It's also possible you'll never need to do this; occasionally some things (like say, a release for 8.10, 8.12, 9.0, whatever...) will tidy themselves up fast. But having an ace in the hole is always good.
