### ISSUE TITLE
Please have a look at the revised edition of the CBOR standard

### ISSUE THREAD

**Issue by cabo** [well-typed/cborg#229]
This is not an issue on your software, but:
I would like to point out that the upcoming editorial revision of RFC
7049, informally called “rfc7049bis”, is in working group last call
right now — if you can spare some time, please have a look at

https://cbor-wg.github.io/CBORbis/draft-ietf-cbor-7049bis.html

and submit any issues (including potential for further improvement of
the text) you might find, at

https://github.com/cbor-wg/CBORbis

Thank you.

Carsten Bormann

**Comment by bgamari** [comment]
Thanks, @cabo!
