### ISSUE TITLE
Releases compatible with GHC 8.10

### ISSUE THREAD

**Issue by sjakobi** [well-typed/cborg#234]
AFAICT the packages in this project are compatible with GHC 8.10 now, so all that's missing is a few revisions and releases. :)

**Comment by sjakobi** [comment]
Ping @bgamari! :)

**Comment by bgamari** [comment]
Done with 0.2.3.0. Thanks for the reminders, @sjakobi!

**Comment by sjakobi** [comment]
@bgamari Could you bump the upper bound on `base` for `cborg-json` on Hackage? Cheers!

**Comment by sjakobi** [comment]
^ Ping @bgamari!

**Comment by bgamari** [comment]
Done!

**Comment by sjakobi** [comment]
Awesome! Many thanks, @bgamari! :)
