### ISSUE TITLE
Decide the eventual fate of this package

### ISSUE THREAD

**Issue by thoughtpolice** [well-typed/cborg#25]
This should be considered a meta ticket for tracking the inevitable replacement of `binary`, and what our plans should be in accomplishing that.

**Comment by Shimuuar** [comment]
This package isn't feature complete replacement for binary. It does replace serialization of haskell values to some format and better at that. But it doesn't allow parsing/serialization to externally defined data formats.

**Comment by thoughtpolice** [comment]
> But it doesn't allow parsing/serialization to externally defined data formats.

This is on the roadmap before they're merged together; there's just no milestone or tickets for this task (I'll make one now). It won't be done before a first public release, either.

**Comment by thoughtpolice** [comment]
See #34

**Comment by bgamari** [comment]
AFAICT `binary` and this package are to a large degree orthogonal: `binary` being a set of low-level primitives to the parsing and encoding of arbitrary binary protocols and this being specifically a library for serialisation in a much more confined encoding. Yes, you can use both to serialise Haskell values, but which is preferable will likely depend upon the application.

Moreover, I'm not sure we're in a position to dictate whether `binary` is superceded or not; that decision lies solely in the hands of users.

**Comment by hvr** [comment]
@bgamari ...are you're suggesting to create a new package, say `binary-ng` to act as the successor of `binary`? ;-)

**Comment by bgamari** [comment]
I'm going to close this as it isn't really actionable.
