### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by sjakobi** [well-typed/cborg#260]
The libraries on `master` seem to be compatible with GHC-9.0.1 now. It would be great to have corresponding releases on Hackage! :)

**Comment by sjakobi** [comment]
Ping @bgamari! :)

**Comment by bgamari** [comment]
@sjakobi, my recollection is that I pushed versions a few weeks ago which should be compatible with GHC 9.0.

**Comment by sjakobi** [comment]
@bgamari The latest [`cborg-json`](http://hackage.haskell.org/package/cborg-json) release definitely isn't compatible. It requires `base < 4.15`.

`cborg` looks compatible though and I haven't checked the other packages.

**Comment by sjakobi** [comment]
Since there haven't been any _code_ changes in `cborg-json` since the latest release, I've used my Hackage trustee powers to create a compatible Hackage revision:

http://hackage.haskell.org/package/cborg-json-0.2.2.0/revisions/

Closing since I'm not aware of any other packages in this project that need releases or revisions.

**Comment by bgamari** [comment]
Thank you @sjakobi!
